# Generated by Django 4.2 on 2026-01-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_origen', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('numero_paginas', models.PositiveIntegerField()),
                ('sinopsis', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('calificacion', models.FloatField(default=0.0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.autor')),
                ('categorias', models.ManyToManyField(to='libros.categoria')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado')], default='activo', max_length=15)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
        ),
    ]
